#!/usr/bin/env node
/* design-md · compile.mjs
   Reads themes/<name>/DESIGN.md → dist/design-md.css + dist/themes.json
   Zero deps. DESIGN.md frontmatter is a fixed shape (see themes/dark-hub).
   Usage: node compile.mjs [theme]   (no arg = all) */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const THEMES = path.join(ROOT, 'themes');
const DIST = path.join(ROOT, 'dist');

/* --- minimal frontmatter parser for the fixed DESIGN.md shape --- */
function parseFrontmatter(src) {
  const m = src.match(/^---\n([\s\S]*?)\n---/);
  if (!m) throw new Error('no frontmatter');
  const out = { fonts: [], tokens: {} };
  let section = null;
  for (const raw of m[1].split('\n')) {
    if (!raw.trim()) continue;
    const indent = raw.length - raw.trimStart().length;
    const line = raw.trim();
    if (indent === 0) {
      if (line === 'fonts:') { section = 'fonts'; continue; }
      if (line === 'tokens:') { section = 'tokens'; continue; }
      section = null;
      const kv = line.match(/^([\w-]+):\s*(.*)$/);
      if (kv) out[kv[1]] = unquote(kv[2]);
    } else if (section === 'fonts') {
      const f = line.match(/^-\s*(.*)$/);
      if (f) out.fonts.push(unquote(f[1]));
    } else if (section === 'tokens') {
      const kv = line.match(/^([\w-]+):\s*(.*)$/);
      if (kv) out.tokens[kv[1]] = unquote(kv[2]);
    }
  }
  return out;
}
const unquote = (s) => s.replace(/^["']|["']$/g, '').trim();

/* --- collect themes --- */
const only = process.argv[2];
const dirs = fs.readdirSync(THEMES)
  .filter((d) => !d.startsWith('_'))
  .filter((d) => fs.existsSync(path.join(THEMES, d, 'DESIGN.md')))
  .filter((d) => !only || d === only);

if (!dirs.length) { console.error('no themes found'); process.exit(1); }

const themes = dirs.map((name) => {
  const fm = parseFrontmatter(fs.readFileSync(path.join(THEMES, name, 'DESIGN.md'), 'utf8'));
  return { name, ...fm };
});

/* --- build CSS --- */
const fontImports = [...new Set(themes.flatMap((t) => t.fonts))]
  .map((u) => `@import url("${u}");`).join('\n');

const core = fs.readFileSync(path.join(ROOT, 'kit', 'core.css'), 'utf8');

const themeBlocks = themes.map((t) => {
  const vars = Object.entries(t.tokens)
    .map(([k, v]) => `  --dm-${k}:${v};`).join('\n');
  return `[data-theme="${t.name}"]{\n${vars}\n}`;
}).join('\n\n');

const css = `/* design-md · dist/design-md.css — GENERATED by compile.mjs. Do not edit.
   ${themes.length} themes: ${themes.map((t) => t.name).join(', ')} */
${fontImports}

${core}
/* ============================================================
   THEMES — compiled from themes/<name>/DESIGN.md
   ============================================================ */
${themeBlocks}
`;

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, 'design-md.css'), css);

/* --- registry for the picker --- */
const registry = themes.map((t) => ({
  name: t.name, label: t.label || t.name,
  swatch: t.swatch || t.tokens.accent || '#888', mode: t.mode || 'dark',
}));
fs.writeFileSync(path.join(DIST, 'themes.json'), JSON.stringify(registry, null, 2));

console.log(`[design-md] compiled ${themes.length} themes → dist/design-md.css (${(css.length / 1024).toFixed(1)}kb)`);
console.log(`[design-md] registry → dist/themes.json`);
